library(shiny)
library(shinyjs)
library(shinythemes)
library(shinyWidgets)
library(bs4Dash)
library(htmltools)
library(shinycssloaders)

library(dplyr)
library(ggplot2)
library(ROCR)
library(xgboost)
library(Ckmeans.1d.dp)

model <- xgb.load("best_model.model")
teste <- read.csv("test.csv")
validation <- read.csv("validation.csv")
